### ISSUE TITLE
ITEM for Beta-Series Correlation (BSC)

### ISSUE THREAD

**Issue by Masharipov** [JoramSoch/ITEM#1]
Dear Joram,

Thanks for your useful ITEM toolbox!

I'm currently comparing task-modulated functional connectivity methods using neural mass simulations. I want to apply your ITEM approach to get trial-wise parameter estimates and then use them for beta-series correlation (BSC).

I first tried to use the gamma parameters estimated by ITEM_est_1st_lvl function. Sensitivity and specificity were similar to BSC-LSA and lower than BSC-LSS. I now suppose that the gamma parameters generated by ITEM_est_1st_lvl function are equivalent to trial-wise parameters estimated by the LSA approach (Eq.4 in your Neuroimage paper). Could you please clarify which equations from the Neuroimage article are used in the ITEM_est_1st_lvl function to calculate gamma_XX.nii files?

Is it correct that I used these parameter estimates? Or is this just the first step in the ITEM approach and the correlation between trials taken into account in subsequent steps and only for decoding/reconstruction? How can I get "uncorrelated" parameter estimates using ITEM toolbox?

Best regards,
Ruslan

**Comment by JoramSoch** [comment]
Dear @Masharipov,

thanks for your message! I think what you describe is a new use case of the ITEM methodology that has not yet been explored.

> I want to apply your ITEM approach to get trial-wise parameter estimates and then use them for beta-series correlation (BSC).

If I understand correctly, you want to calculate trial-wise parameter estimates, and then simply correlate those over trials (e.g. seed-based where one voxel/ROI is the reference, with respect to which you correlate everything else).

> I now suppose that the gamma parameters generated by ITEM_est_1st_lvl function are equivalent to trial-wise parameters estimated by the LSA approach (Eq.4 in your Neuroimage paper).

That is correct. It is a frequent misunderstanding that the ITEM Toolbox somehow delivers "cleaned" or "optimized" trial-wise parameter estimates. The estimates from `ITEM_est_1st_lvl` are pure LS-A estimates (NeuroImage paper, eq. 4) and there is no magic.

> Is it correct that I used these parameter estimates? Or is this just the first step in the ITEM approach and the correlation between trials taken into account in subsequent steps and only for decoding/reconstruction?

Yes, right. The magic happens at the second level when you set up a linear decoding model which extracts experimental conditions or parametric variables from the multivariate signals (NeuroImage paper, eqs. 10, 11, 13) -- and this is the step where the correlations are being accounted for (by using the uncorrelation matrix as the model's covariance matrix; eq. 8).

> How can I get "uncorrelated" parameter estimates using ITEM toolbox?

In theory, not at all (because the design matrix also needs to be uncorrelated [or "whitened", how it is usually called]). However, in your use case, it might be possible, because there is no such thing as the design matrix and you just want to correlate between voxels.

What you would have to do then, is to re-calculate the session-wise uncorrelation matrix into a whitening matrix which whitens the signals and hence, removes trial-by-trial correlations. Here is a code snippet that would give you such whitened trial-wise parameter estimates (at least for me, this worked).

```matlab
spm fmri
% specify path to SPM model
path_to_your_SPM_model = 'C:\Joram\projects\BCCN\VisRec\Soch_et_al_2020\data\sub-AAA02\mods\glms-item\glm-full';
load(strcat(path_to_your_SPM_model,'/SPM.mat'));
% load trial-wise parameter estimates
G = ITEM_load_gammas(SPM); % sum(GLM1.tr) x voxels matrix
load(strcat(path_to_your_SPM_model,'/ITEM_est_1st_lvl/GLM1.mat'));
% calculate "uncorrelated" parameter estimates
Gu = zeros(size(G)); % sum(GLM1.tr) x voxels matrix
for i = 1:numel(GLM1.Sess)
    % calculate and apply whitening matrix
    W = sqrtm(inv(GLM1.Sess(i).U));
    Gu(GLM1.Sess(i).t,:) = W * G(GLM1.Sess(i).t,:);
end;
% remove nuisance variables, restrict to trials
Gut = zeros(sum(GLM1.t),size(Gu,2)); % sum(GLM1.t) x voxels matrix
t   = 0;
for i = 1:numel(GLM1.Sess)
    Gut((t+1):(t+GLM1.t(i)),:) = Gu(GLM1.Sess(i).t(1:GLM1.t(i)),:);
    t = t + GLM1.t(i);
end;
```

If you have questions about the operations applied here, don't hesitate to ask! I'll leave this issue open, so you can report back whether what I suggested made sens. Otherwise, I hope it helps.

Cheers
Joram

**Comment by Masharipov** [comment]
Dear Joram,

Thanks for the detailed answer!

I implemented your code to calculate the whitening matrix W from the uncorrelation matrix U and applied it to trial-wise paramter estimates G (Gu = G*W). Next, I used the 'uncorrelated' paramer estimates Gu for beta-series correlation (BSC). Unfortunately, the increase in sensitivity (I control the ground truth task-modulated functional connectivity via large-scale neuronal mass simulations) was only 1% compared to using 'raw' paramer estimates G (i.e., the LSA approach).

I guess the the uncorrelation matrix U does the magic trick for decoding/reconstruction, but may not work well for BSC.

Anyway, thanks so much for your help!
Best,
Ruslan

**Comment by JoramSoch** [comment]
Dear Ruslan,

thanks for your reply! I would consider using the variable `Gut` (rather than `Gu`) for your correlation analyses, as it does not include coefficients of nuisance variables (though I don't know for sure whether you used nuisance variables in your simulation). In the [NeuroImage paper](https://www.sciencedirect.com/science/article/pii/S1053811919310407), this is explained in Section 2.4 and Figure 1B (see below).

Calculating correlations across the whole gamma vector does not make sense in my eyes, as nuisance variables are not trials and will likely act like outlier values, potentially distoring the correlations. That is is why I restricted the gamma matrix to trial entries in the last step in my code. In `GLM1.mat`, this is the difference between `GLM1.t` and `GLM1.tr` in case you want to check.

Cheers
Joram

---

![image](https://github.com/user-attachments/assets/9504bb55-eb37-48f1-9ea0-3e9b6c00a39c)
![image](https://github.com/user-attachments/assets/f9bc0a4c-4f2c-4853-a8db-55c2fdbe16eb)

**Comment by Masharipov** [comment]
Dear Joram,

Sorry for the misunderstanding, I actually used **Gut** instead of **Gu**. However, in my case, Gut and Gu were identical (indeed, I didn't use nuisance variables in my simulations). So, unfortunately, this was not the reason why I didn't find a significant increase in sensitivity compared to the LSA approach (as applied to the BSC analysis).

Thank you for help! 
Best,
Ruslan

**Comment by JoramSoch** [comment]
Dear Ruslan,

thanks for letting me know! I don't have an explanation for the results you see (except that maybe, the ISIs in your simulation analysis are long enough for trial-wise parameter estimates not being substantially correlated, i.e. no big difference between LS-A and "uncorrelated" LS-A). At some point, I also want to look into this topic with own simulations, but don't know when this will happen. But thanks for trying out at this point already...

Cheers
Joram

**Comment by Masharipov** [comment]
Dear Joram,

I tested "uncorrelated" LSA (ULSA) on a simulation with the mean ISI = 6s (event duration = 1s). In this case, BSC-LSS was twice as sensitive as BSC-LSA and BSC-ULSA. I also tested BSC-ULSA on a simulation with the mean ISI  = 2s. In this case, the difference between BSC-LSS and BSC-ULSA becomes even more noticeable. Nevertheless, if you think out a solution for BSC based on the uncorrelation matrix U, please write to me so I can test it in my simulations (old version of the preprint with simulations is available here: https://doi.org/10.1101/2024.01.22.576622). 

Best,
Ruslan

**Comment by JoramSoch** [comment]
OK, thanks! Although the ISI = 6s is quite high, the fact that LS-S clearly outperforms LS-A (and ITEM) means that there is correlation that can be removed/accounted for. As I said, I'm going to look into this when I have time. Thanks for the preprint link!
